version: '3'
services:
  nginx_ssl:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/opt/nginx
      - ./cert:/opt/nginx/cert